name: hanoi_tower_game
description: A Hanoi Tower Game written in Flutter

version: 0.0.1

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^0.5.8

  cupertino_icons: ^0.1.2

  hanoi_tower_control:
    git:
      url: git@github.com:lairmartes/hanoi_tower_control.git
      ref: master

  eventify: ^0.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.7.3
  flutter_launcher_name: ^0.0.1

  mockito: ^4.1.1

flutter_icons:
  image_path: "icon/icon.png"
  android: true
  ios: true

flutter_launcher_name:
  name: "Hanoi Tower"

flutter:
  assets:
    - images/levels/level_1.png
    - images/levels/level_2.png
    - images/levels/level_3.png
    - images/levels/level_4.png
    - images/levels/level_5.png
    - images/levels/level_6.png
    - images/levels/level_7.png
    - images/levels/level_8.png
    - images/levels/level_9.png
    - images/levels/level_10.png

  uses-material-design: true


