name: hanoi_tower_game
description: A Hanoi Tower Game written in Flutter

version: 0.0.1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

  hanoi_tower_control:
    git:
      url: git@github.com:lairmartes/hanoi_tower_control.git
      ref: master


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

